version: '3'

services:
  posts-postgres:
    container_name: posts-postgres
    image: postgres
    ports: 
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres:password@postgres:5432
      PORT: 3000
    depends_on: 
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posts